### ISSUE TITLE
Initial Data

### ISSUE THREAD

**Issue by TBSliver** [Pear-Trading/Foodloop-Server#2]
Require some initial data to be set up in the database:

* Age Range
  * The following values need to be in the AgeRange table: `20-35` `35-50` `50+`
* Initial tokens
  * We need some initial tokens in the database before we can do anything - for development they dont need to be anything major.

**Comment by MichaelHallam** [comment]
I will email you a list of names of players with age ranges
Please define more clearly what you mean my "tokens"

**Comment by MichaelHallam** [comment]
..just emailed you some age range data.
